FROM nodered/node-red:1.2.7
RUN npm install node-red-contrib-advanced-ping
RUN npm install node-red-contrib-isonline
RUN npm install node-red-contrib-mikrotik
RUN npm install node-red-contrib-telegrambot


